const ActionTypes = {
    FETCH_SHOP_DATA_START : 'FETCH_SHOP_DATA_START',
    FETCH_SHOP_DATA_SUCCESS : 'FETCH_SHOP_DATA_SUCCESS',
    FETCH_SHOP_DATA_FAILURE : 'FETCH_SHOP_DATA_FAILURE',
    INIT_SHOP: 'INIT_SHOP'
}

export default ActionTypes;